language: node_js
matrix:
  include:
    - os: osx
      env: BUILD_SCRIPT=build:mac
    - os: linux
      sudo: required
      dist: trusty
      env: BUILD_SCRIPT=build:linux
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build:dist
  - npm run ${BUILD_SCRIPT}
notifications:
  slack:
    on_success: never