sudo: required
dist: trusty
language: node_js
matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build:dist
  - npm run build:linux