sudo: required
dist: trusty
language: node_js
matrix:
  include:
    - os: osx
    - os: linux
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build:dist
  - os: linux
    - npm run build:linux