os: unstable
cache:
  - node_modules
environment:
  matrix:
    - nodejs_version: 9
    - npm_version: 9
install:
  - ps: Install-Product node $env:nodejs_version
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version