name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 9.x
          check-latest: true

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          git lfs pull
          npm run validate-files
          npm run build:dist
          
      - name: Build Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: npm run build:linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      - name: Build Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Build Mac
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
